---
- name: Create Packer AEM CI on AWS CodeBuild and CodePipeline
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    - name: Ensure stage directory exists
      file: path=../../../stage/ci-aws/ state=directory

    - name: Generate Packer AEM CodeBuild project input JSON files
      template:
        src: packer-aem/codebuild-project.j2
        dest: ../../../stage/ci-aws/packer-aem-codebuild-{{ item[0] | replace("/", "-") | replace(".", "-") }}-{{ item[1].platform_type }}-{{ item[1].os_type }}-{{ item[2] }}-{{ item[3] }}.yaml
        mode: 0644
      with_nested:
        - "{{ scm.repos.packer_aem.branches }}"
        - "{{ ci.aws.hosts }}"
        - "{{ ci.aws.aem_versions }}"
        - "{{ ci.aws.components }}"

    - name: Create Packer AEM CodeBuild projects
      shell: |
        aws codebuild create-project \
        --name packer-aem-{{ item[0] | replace("/", "-") | replace(".", "-") }}-{{ item[1].platform_type }}-{{ item[1].os_type }}-{{ item[2] }}-{{ item[3] }} \
        --cli-input-json file://../../../stage/ci-aws/packer-aem-codebuild-{{ item[0] | replace("/", "-") | replace(".", "-") }}-{{ item[1].platform_type }}-{{ item[1].os_type }}-{{ item[2] }}-{{ item[3] }}.yaml \
        --region {{ aws.region }} \
        --badge-enabled
      with_nested:
        - "{{ scm.repos.packer_aem.branches }}"
        - "{{ ci.aws.hosts }}"
        - "{{ ci.aws.aem_versions }}"
        - "{{ ci.aws.components }}"

    - name: Generate Packer AEM CodePipeline pipeline input JSON files
      template:
        src: packer-aem/codepipeline-pipeline.j2
        dest: ../../../stage/ci-aws/packer-aem-codepipeline-{{ item[0] | replace("/", "-") | replace(".", "-") }}-{{ item[1].platform_type }}-{{ item[1].os_type }}-{{ item[2] }}.yaml
        mode: 0644
      with_nested:
        - "{{ scm.repos.packer_aem.branches }}"
        - "{{ ci.aws.hosts }}"
        - "{{ ci.aws.aem_versions }}"

    - name: Create Packer AEM CodePipeline pipelines
      shell: |
        aws codepipeline create-pipeline \
        --cli-input-json file://../../../stage/ci-aws/packer-aem-codepipeline-{{ item[0] | replace("/", "-") | replace(".", "-") }}-{{ item[1].platform_type }}-{{ item[1].os_type }}-{{ item[2] }}.yaml \
        --region {{ aws.region }}
      with_nested:
        - "{{ scm.repos.packer_aem.branches }}"
        - "{{ ci.aws.hosts }}"
        - "{{ ci.aws.aem_versions }}"
