---
- name: Delete Packer AEM CI on AWS CodeBuild and CodePipeline
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    - name: Delete Packer AEM CodePipeline pipelines
      shell: |
        aws codepipeline delete-pipeline \
        --name packer-aem-{{ item[0].platform_type }}-{{ item[0].os_type }}-{{ item[1] }} \
        --region {{ aws.region }}
      with_nested:
        - "{{ ci.aws.hosts }}"
        - "{{ ci.aws.aem_versions }}"

    - name: Delete Packer AEM CodeBuild projects
      shell: |
        aws codebuild delete-project \
        --name packer-aem-{{ item[0].platform_type }}-{{ item[0].os_type }}-{{ item[1] }}-{{ item[2] }} \
        --region {{ aws.region }}
      with_nested:
        - "{{ ci.aws.hosts }}"
        - "{{ ci.aws.aem_versions }}"
        - "{{ ci.aws.components }}"
